FROM hashicorp/terraform:latest

RUN apk add util-linux

WORKDIR /keycloak-init

COPY keycloak/main.tf ./main.tf
COPY keycloak/run-terraform.sh ./run-terraform.sh

ENTRYPOINT ["/bin/sh", "run-terraform.sh"]
