#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U postgres <<-EOSQL
    CREATE USER app WITH PASSWORD '$POSTGRES_APP_PASSWORD';
    CREATE DATABASE app OWNER app;

    CREATE USER keycloak WITH PASSWORD '$POSTGRES_KEYCLOAK_PASSWORD';
    CREATE DATABASE keycloak OWNER keycloak;

    CREATE USER terraform WITH PASSWORD '$POSTGRES_TERRAFORM_PASSWORD';
    CREATE DATABASE terraform OWNER terraform;
EOSQL
